# Generated by Django 5.2.6 on 2025-12-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0006_delete_pessoa_delete_post_delete_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_edicao', models.DateTimeField(auto_now_add=True)),
                ('id_informacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('token_item', models.CharField(max_length=255)),
                ('informacoes_editadas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edited_items',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('id_informacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('token_produto', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('preco', models.FloatField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=255, null=True)),
                ('validade', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='QuickToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
            ],
            options={
                'db_table': 'quick_tokens',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('funcao', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
