# Generated by Django 5.2.6 on 2025-12-09 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editeditem',
            options={'ordering': ['-data_edicao'], 'verbose_name': 'Item Editado', 'verbose_name_plural': 'Itens Editados'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='quicktoken',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Token Rápido', 'verbose_name_plural': 'Tokens Rápidos'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='editeditem',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.product', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='product',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Imagem'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade em Estoque'),
        ),
        migrations.AddField(
            model_name='quicktoken',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='quicktoken',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='editeditem',
            name='data_edicao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Edição'),
        ),
        migrations.AlterField(
            model_name='editeditem',
            name='id_informacoes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Informações'),
        ),
        migrations.AlterField(
            model_name='editeditem',
            name='informacoes_editadas',
            field=models.TextField(blank=True, null=True, verbose_name='Informações Editadas'),
        ),
        migrations.AlterField(
            model_name='editeditem',
            name='token_item',
            field=models.CharField(max_length=255, verbose_name='Token do Item'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_informacoes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Informações'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='token_produto',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Token do Produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Volume/Tamanho'),
        ),
        migrations.AlterField(
            model_name='quicktoken',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='quicktoken',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='quicktoken',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='quicktoken',
            name='expira_em',
            field=models.DateTimeField(verbose_name='Expira em'),
        ),
        migrations.AlterField(
            model_name='quicktoken',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='funcao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='senha',
            field=models.CharField(max_length=255, verbose_name='Senha'),
        ),
    ]
